name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.6
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: cp -f README.md dist/
      - run: pnpm run lint && pnpm run build
